name: Notify Slack on Push

on:
  push:
    branches:
      - main

jobs:
  call-slack:
    uses: ./.github/workflows/slack-notify-reusable.yml
    with:
      message: "ðŸŽ‰ New push to *main* by ${{ github.actor }}\n> Commit: ${{ github.event.head_commit.message }}"
      color: "#ff69b4" # bright pink
      channel: "C09R47WGPMW"
